module.exports = {
  preset: 'ts-jest',
  clearMocks: true,
  moduleNameMapper: {
    '\\.(css|less|scss|sass)$': 'identity-obj-proxy',
    '^app(.*)$': '<rootDir>/src/app$1',
    '^pages(.*)$': '<rootDir>/src/pages$1',
    '^widgets(.*)$': '<rootDir>/src/widgets$1',
    '^features(.*)$': '<rootDir>/src/features$1',
    '^entities(.*)$': '<rootDir>/src/entities$1',
    '^shared(.*)$': '<rootDir>/src/shared$1',
  },
  coveragePathIgnorePatterns: ['/node_modules/'],
  moduleDirectories: ['src', 'node_modules'],
  setupFilesAfterEnv: [
    '<rootDir>/config/jest/jest.setup.ts',
    '@testing-library/jest-dom/extend-expect',
  ],
  moduleFileExtensions: [
    'js',
    'mjs',
    'cjs',
    'jsx',
    'ts',
    'tsx',
    'json',
    'node',
  ],
  rootDir: '../../',
  testEnvironment: 'jsdom',
  testMatch: ['<rootDir>src/**/*(*.)@(spec|test).[tj]s?(x)'],
}
